XENONnT/fuse

.github/workflows/python_publish.yml, .gitignore, README.md
Adding pypi build workflow to https://pypi.org/project/xenon-fuse/.
=> PyPI build

docs/source/detector_physics.rst, docs/source/plugins/detector_physics/ChunkCsvInput.rst, fuse/plugins/detector_physics/csv_input.py, tests/_utils.py, tests/test_DetectorPhysics_csv.py
PR to fix https://github.com/XENONnT/fuse/issues/130
=> CSV input plugin update

fuse/plugins/detector_physics/s1_photon_propagation.py
PR to fix https://github.com/XENONnT/fuse/issues/145
=> Prevent empty instructions to lock NEST random seed

examples/0_Getting_Started.ipynb, examples/1_Microphysics_Simulation.ipynb, examples/2_Detectorphysics_Simulation.ipynb, examples/3_csv_input.ipynb, examples/4_Custom_Simulations.ipynb, fuse/context.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/detector_physics/secondary_scintillation.py, fuse/plugins/pmt_and_daq/photon_pulses.py, fuse/plugins/pmt_and_daq/pmt_response_and_daq.py, tests/test_DetectorPhysics_csv.py, tests/test_FullChain.py, tests/test_deterministic_seed.py, tests/test_plugin_versions_in_doc.py
This PR will implement the changes discussed in https://github.com/XENONnT/fuse/issues/134 and https://github.com/XENONnT/fuse/issues/126
=> Handle missing corrections_version and cleanup

docs/source/plugins/micro_physics/ChunkInput.rst, fuse/plugins/micro_physics/input.py
This PR tries to move the changes from https://github.com/XENONnT/fuse/pull/154 into the data loading with uproot.
=> Move eventid cut into uproot data loading

fuse/context.py
=> Make s2 AFT scaling optional

fuse/plugins/micro_physics/input.py, tests/test_input.py
... once and for all 😅 
See https://github.com/XENONnT/fuse/pull/166.
Thanks to @mhliu0001 and sorry for overlooking this.
=> Fixing `entry_stop` selection

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, fuse/plugins/micro_physics/input.py, pyproject.toml
=> Release 1.2.1

.github/workflows/pytest.yml, tests/test_DetectorPhysics_csv.py
This PR sets the test timeout (from 15 minutes) to 30 minutes.
=> Increase test timeout to 30 minutes

fuse/plugins/micro_physics/yields.py, tests/test_FullChain.py, tests/test_MicroPhysics.py, tests/test_clustering_functions.py, tests/test_common_functions.py, tests/test_truth_plugins.py, tests/test_waveform_building_functions.py
This PR will add a bunch of additional tests to fuse. 
=> Add more tests

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
=> Release 1.2.3

fuse/plugins/truth_information/cluster_tagging.py
=> Add descriptions of dtypes in `tagged_clusters`

.github/workflows/pytest.yml, fuse/plugins/detector_physics/electron_drift.py
=> Remove unused codes and fix nestpy commit hash

fuse/plugins/detector_physics/csv_input.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_drift.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_extraction.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_merger.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_s1photonhits.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_secondary_scintillation.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_timing.py, fuse/plugins/detector_physics/delayed_electrons/photo_ionization_electrons.py, fuse/plugins/detector_physics/electron_drift.py, fuse/plugins/detector_physics/electron_extraction.py, fuse/plugins/detector_physics/electron_timing.py, fuse/plugins/detector_physics/s1_photon_hits.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/detector_physics/secondary_scintillation.py, fuse/plugins/micro_physics/detector_volumes.py, fuse/plugins/micro_physics/electric_field.py, fuse/plugins/micro_physics/find_cluster.py, fuse/plugins/micro_physics/input.py, fuse/plugins/micro_physics/lineage_cluster.py, fuse/plugins/micro_physics/merge_cluster.py, fuse/plugins/micro_physics/merge_lineage.py, fuse/plugins/micro_physics/wfsim_connection.py, fuse/plugins/micro_physics/yields.py, fuse/plugins/pmt_and_daq/photon_pulses.py, fuse/plugins/pmt_and_daq/pmt_afterpulses.py, fuse/plugins/pmt_and_daq/pmt_response_and_daq.py
This PR aims at fixing logging messages that did not show up during the simulation. The problem is described here: https://github.com/XENONnT/fuse/issues/247
=> Fix plugin warning/debug/info logging

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
=> Release 1.4.1

.github/scripts/create_readonly_utilix_config.sh
Similar to https://github.com/XENONnT/straxen/pull/1433
=> utilix>0.9 compatibility

pyproject.toml, tests/test_FullChain.py, tests/test_FullChain_w_DelayedElectrons.py, tests/test_MicroPhysics.py, tests/test_MicroPhysics_with_lineage_clustering.py, tests/test_deterministic_seed.py, tests/test_input.py, tests/test_plugin_random_seed.py, tests/test_truth_plugins.py
See this PR: https://github.com/XENONnT/utilix/pull/141
=> Import MongoDownloader from utilix

pyproject.toml
The trailing release before switching to higher strax(en).
=> Constraint strax(en) to be less than 2.0.0(3.0.0)

.bumpversion.cfg, .pre-commit-config.yaml
Follow changes shown in https://github.com/XENONnT/straxen/pull/1453
=> Use master for docformatter

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
Final fuse release before strax >= 2.x.x and straxen >= 3.x.x .
=> Release 1.4.3

fuse/context.py, fuse/plugins/detector_physics/csv_input.py, fuse/plugins/micro_physics/input.py, pyproject.toml
But before this, there should be a final stage release of fuse with strax<2, straxen<3.
=> Be compatible with straxen >= 3

.github/workflows/pytest.yml, .readthedocs.yml, fuse/plugins/detector_physics/s1_photon_hits.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/detector_physics/secondary_scintillation.py, fuse/plugins/pmt_and_daq/pmt_afterpulses.py, fuse/plugins/truth_information/peak_truth.py, fuse/plugins/truth_information/records_truth.py, pyproject.toml, tests/test_plugin_random_seed.py
Similar to https://github.com/XENONnT/cutax/pull/505 and https://github.com/XENONnT/straxen/pull/1235
=> Remove CMT URLs, drop python 3.9

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
=> Release 1.5.0

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
=> Release 1.5.1

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
Release 1.5.2. 
Yes, the third release in a week.
=> Release 1.5.2

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
Make new release for SR2 simulations.
=> Release v1.5.6

fuse/plugins/micro_physics/merge_lineage.py
=> Make sure `clustered_interactions` is sorted

fuse/dtypes.py, fuse/plugins/detector_physics/csv_input.py, fuse/plugins/micro_physics/merge_cluster.py, fuse/plugins/micro_physics/merge_lineage.py
=> Save `t` in `clustered_interactions` and `microphysics_summary`
