XENONnT/fuse

.github/workflows/pytest.yml
When running coveralls, just report the pytest result rather than running pytest again.
=> Simplify pytest and coveralls to shorten time usage

fuse/plugins/detector_physics/electron_drift.py, fuse/plugins/detector_physics/s2_photon_propagation.py
Currently in `straxen`, we have three interpolation methods: `RectBivariateSpline`, `RegularGridInterpolator`, `WeightedNearestNeighbors`. I propose we should avoid `RectBivariateSpline` since it creates unphysical values. The `RegularGridInterpolator` may also create unphysical values for values out of range (extrapolated), but it is faster and more straightforward than `WeightedNearestNeighbors`.
So we should use `RegularGridInterpolator` if it yields similar results to `WeightedNearestNeighbors`, and if the data are constructed on a regular bin. Otherwise we should use `WeightedNearestNeighbors`.
See [this note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:miliu:fuse_civ_interpolation#interpolation_method_for_fuse_maps) for more plots to validate these changes.
Solves #151.
=> Changes in interpolation methods

fuse/plugins/detector_physics/s2_photon_propagation.py
This PR fixes https://github.com/XENONnT/fuse/issues/86. It turned out that the problem was caused by the addition of int64 values to float64 values for the timing. 
The first plot shows the electron and s2 photon times before the fix: 
After the fix the times are not spaced in these discrete steps:
=> Convert _photon_timings to integer values

docs/source/plugins/pmt_and_daq/PMTResponseAndDAQ.rst, fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/pmt_and_daq/pmt_response_and_daq.py, tests/test_DetectorPhysics_csv.py
In the previous code, the `compute` function for downchunking plugins (S2PhotonPropagationBase, PMTResponseAndDAQ) has some duplicate code. While I understand this is because the chunking start/end times are different, it can be avoided by defining a function `compute_chunk`, and calling it to calculate the data in each chunk.
This PR should not alter the behavior of fuse and should be purely cosmetic. If the simulation results change, please let me know.
=> Avoid duplicate code in downchunking

fuse/plugin.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/micro_physics/yields.py, tests/test_plugin_random_seed.py
With this PR we will give users the option to set the random seed manually. If you want to use this function, you need to set `deterministic_seed` to `False` and `user_defined_random_seed` to the seed you want to use.
=> Optional random seed as user input

examples/5_Simulation_Truth.ipynb, fuse/__init__.py, fuse/dtypes.py, fuse/plugins/detector_physics/csv_input.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_s1photonhits.py, fuse/plugins/detector_physics/electron_drift.py, fuse/plugins/detector_physics/electron_extraction.py, fuse/plugins/detector_physics/electron_timing.py, fuse/plugins/detector_physics/s1_photon_hits.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/micro_physics/detector_volumes.py, fuse/plugins/micro_physics/electric_field.py, fuse/plugins/micro_physics/find_cluster.py, fuse/plugins/micro_physics/input.py, fuse/plugins/micro_physics/merge_cluster.py, fuse/plugins/micro_physics/wfsim_connection.py, fuse/plugins/micro_physics/yields.py, fuse/plugins/pmt_and_daq/pmt_afterpulses.py, fuse/plugins/truth_information/cluster_tagging.py, fuse/plugins/truth_information/event_truth.py, fuse/plugins/truth_information/peak_truth.py, tests/test_input.py
Similar to https://github.com/XENONnT/fuse/pull/147, but I added a type manager for all plugins.
1. please look at `fuse/dtypes.py` for all lists of fields
2. remove `". Will be set later"` from dtype of `clustered_interactions`
3. add `csv_input_fields` indicating the needed fields for `ChunkCsvInput`
This PR will also remove the trouble of updating the same field distributed in different files later.
=> Add a dtypes manger

fuse/context.py, fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/detector_physics/secondary_scintillation.py
This PR modifies the code of s2_aft_rescaling of s2 pattern by setting dead PMTs to be zero before rescaling, otherwise the aft could be changed even after the rescaling.
=> Scale S2 pattern map to correct S2 AFT

fuse/common.py, fuse/plugins/detector_physics/s2_photon_propagation.py
Do not return photons if all PMTs have no probability of being hit or if all electrons in a cluster are outside the TPC. In these cases, channel number is assigned negative. Only take photons with positive channel number
Solves the Issue #199 
If there are no electrons extracted within the TPC, when calculating the average position of all electrons in the cluster of extracted electrons (in this case 0), the PMT patter probability distribution is filled with not-a-number values. If this is the case, for each photon that was calculated to be emitted by the extracted electrons, the channel number is set to be -1.
If this PR is accepted, at the end of the plugin, …
=> No photons from electrons outside

examples/2_Detectorphysics_Simulation.ipynb, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_merger.py, fuse/plugins/detector_physics/delayed_electrons/delayed_electrons_s1photonhits.py, fuse/plugins/detector_physics/s1_photon_hits.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/truth_information/peak_truth.py, tests/test_FullChain.py, tests/test_FullChain_w_DelayedElectrons.py
This PR renames the output of the `S1PhotonHits` plugin from `"s1_photons"` to `"s1_photon_hits"` to avoid confusion with the dtype of the propagated s1 photons. 
=> Rename s1 photon hits output

fuse/dtypes.py
This PR changes the dtype for Geant4 times back to float64. 
=> Change dtype for time input back to float64

fuse/plugins/truth_information/event_truth.py
The plugin now returns x, y, and z truth values defined. The difference between these and the `_obs_truth` values is the same as the difference between `average_<coord>_of_contributing_clusters` and `average_<coord>_obs_of_contributing_clusters` from peak_truth plugin.
The few lines this PR adds to the `event_truth` plugin simply add  `average_x_of_contributing_clusters` and  `average_y_of_contributing_clusters` of the main S2 peak of the current event as the `x_truth` and `y_truth` values in the result.
Furthermore, it adds the mean of the  `average_z_of_contributing_clusters` of the main S1 and S2 peaks of the event as `z_truth`, by following the same logic …
=> Add x_truth, y_truth, z_truth

README.md, fuse/plugins/truth_information/cluster_tagging.py
This PR adds some fields in `ClusterTagging` plugin based only on peaks. The new fields don't tell you whether the peaks are main/alternative but only S0/S1/S2 and the tight coincidence of the peaks. This definition is consistent with the reconstruction efficiency.
I also added a new parameter `photon_finding_window` as the window of `touching_window_split`. This is because that there are some photons reconstructed as peaks successfully, but the peaks' start and end times are both later than the photon time (i.e. the cluster time) thus it cannot be tagged if we simply use `window=0`. Currently it's set to 200ns, meaning peaks' start and end times are extended both 200ns to find photons.
=> Add tight coincidence and peak tagging in `ClusterTagging`

.gitignore, docs/doc_requirements.txt, docs/source/build_plugin_pages.py
Before this PR, when running
```
make html
```
in folder `fuse/docs`, error shows:
```
Exception occurred:
File "/opt/miniconda3/envs/XENONnT_2024.03.1/lib/python3.9/shutil.py", line 722, in rmtree
orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/xudc/fuse/docs/source/graphs'
```
this is because the `"graphs"` folder is not defined correctly in `shutil.rmtree`
Define a unified path of graphs.
=> Fix bug when building docs locally

fuse/plugins/detector_physics/csv_input.py, fuse/plugins/micro_physics/input.py
`data_type` of `ChunkInput` should not be "geant4_interactions"
=> Fix `ChunkCsvInput` data_type of chunk

fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/pmt_and_daq/pmt_response_and_daq.py, tests/test_waveform_building_functions.py
The main problem in the codes before this PR:
This line https://github.com/XENONnT/fuse/blob/d5dde954301e12ebb6ec282297d98a23d47eba76/fuse/plugins/pmt_and_daq/pmt_response_and_daq.py#L380 will run `argwhere` for each `pulse["pulse_id"]`.
When the length of `unique_photon_pulse_ids` O(1e6). The running time is intolerable.
This PR first chunks the photons and then pre-processes the photons, so the first two arguments of `build_waveform`: `pulse_windows` and `photons` will have the same length. Then we do not need to run `argwhere`.
[branch name](https://jojo.fandom.com/wiki/Made_in_Heaven)
=> Raw Records simulation acceleration in Fuse

fuse/plugins/pmt_and_daq/photon_pulses.py
Fix https://github.com/XENONnT/fuse/issues/229
And a problem with sorting of `photon_pulses` and `pulse_ids`.
In previous codes
https://github.com/XENONnT/fuse/blob/9baffd35a1aa09ead198817b81555b7125264381/fuse/plugins/pmt_and_daq/photon_pulses.py#L131
`photon_pulses` is sorted before assigning `photon_id` to `pulse_ids`.
Similar to https://github.com/XENONnT/straxen/blob/b8fe520deca55b8c5ac0cb53249b38639f0ae5de/straxen/plugins/events/events.py#L154, first make an attribute `pulse_ids_seen` of `PulseWindow`, then update it for each chunk.
=> Make `pulse_id` continuous in chunks

fuse/common.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/detector_physics/s2_photon_propagation.py
This PR relax the requirement that photon gains must be positive. This is because for the reconstruction bias we are interested is the `peak_area / num_photoelectrons - 1`. The under-amplified photons still contribute PEs and dropping them before the truth plugin can affect the result.
After fixing this, we have consistent result with SR0 WFSim result. Check [the notebook](https://github.com/XENONnT/analysiscode/blob/master/SR1_fuse_matching/peak_recon_bias.ipynb) for details.
=> Keep negative gain photons

.bumpversion.cfg, HISTORY.md, fuse/__init__.py, pyproject.toml
=> Release 1.3.0

pyproject.toml
There is a problem with the latest numpy version and pandas. This PR will fix the numpy version to be equal or smaller than 1.26.0. Also see: https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from
=> fix numpy version

fuse/plugins/micro_physics/input.py
This PR adds the option to distribute events with a fixed timing instead of using a uniform distribution.
Setting the tracked config argument `fixed_event_spacing` from the default value `false` to `true` will set the event timings to fixed values. The event spacing is controlled by the `source_rate` argument. 
=> Add option to distribute Geant4 events with fixed timing

fuse/dtypes.py
Because the maximum for int8 is 127, we get overflows when representing for example A=212 ( goes to -44). 
Moving to int16 should have no big impact and will solve the issue.
=> Update mass and charge dtypes to int16

fuse/plugins/detector_physics/s1_photon_propagation.py
This PR will exchange the number of excitons in the S1 timing simulation by the ratio of excitons to photons. It aims at solving https://github.com/XENONnT/fuse/issues/239. It is an alternative to https://github.com/XENONnT/fuse/pull/249.
=> Exciton ratio fix

pyproject.toml
Similar to https://github.com/XENONnT/axidence/pull/85
=> Poetry does not understand `requires-python`

fuse/plugins/micro_physics/lineage_cluster.py
With this PR we fix some issues with the treatment of RadioactiveDecayBase (RDB) interactions. I realised that the results of simulating one gamma and simulating the gamma from Xe131 gave very different results. That is not good. Now they both give similar results. 
Specifically, we had to add special treatment for gammas emitted from excited nuclei that are treated by RDB library. 
Low energy gammas will not produce a gamma-phot/compt interaction in G4 just like hig energy gammas, but just some electron tracks and some gamma tracks will be produced. Now, we decide based on the secondaries what yield to assign to a certain cluster. The modifications match perfectly the distributions of Xe129 and Xe133 ( they were completely off before this PR ) and also match much better Pb212. 
- If …
=> Fix lineage algo - RadioactiveDecayBase

fuse/plugins/pmt_and_daq/photon_pulses.py
While checking out why I am getting `numpy.exceptions.DTypePromotionError: field titles of field 'pulse_id' mismatch` I found this error with Henning and after changing the casting to be consistent it seems to have vanished.
=> pulse_id type casting inconsistency

examples/4_Custom_Simulations.ipynb, fuse/context.py
This PR adds a URLConfig protocol, creating a dummy map returning constant values. The DummyMap code is taken from [WFSim](https://github.com/XENONnT/WFSim/blob/b75494fbd594c329eee54535b0bb9754bc7458d8/wfsim/load_resource.py#L437-L457).
=> Option to replace maps by constant dummy map

fuse/plugins/detector_physics/s2_photon_propagation.py
We increase the default value for the `min_electron_gap_length_for_splitting`.  This defines the time windows to split chunks at s2 photon propagation.
This was creating issues when afterpulses of large S2s would go out of the chunk boundaries. For some high energy simulations (BiPos with ~5k events/job) this was having a fail rate of ~50% of jobs submitted. With the new configuration the issue now appears less than 1%. 
The errors would be of the type: 
```
ValueError: Attempt to create chunk (00009.pulse_windows: 1565sec 869075581 ns - 1777sec 483266062 ns, 74217 items, 0.0 MB/s) whose data ends late at 1777483266961
```
and it created problems with different plugins, see here out of 393 submittet jobs the plugin that failed:
```
Total number of files scanned: 393
Total number of files …
```
=> Fix chunk ends late issue

fuse/plugins/detector_physics/delayed_electrons/photo_ionization_electrons.py
`photoionization_time_cutoff` is the cutoff when modeling `photoionization_modifier`. `photoionization_modifier `will be smaller when cutoff is smaller because analysts only look at a part of the distribution not the whole one.
`photoionization_time_cutoff_mc` is the cut off choosen to simulate only a part of the photoionization distribution to make simulation faster. By setting `photoionization_time_cutoff_modeling` smaller than `photoionization_time_cutoff_mc`, you will simulate "less PI". The PI strength or time constant will not be changed.
=> Only simulate a part of the PI train

.github/workflows/pytest.yml
All fuse tests fail now because of a problem with cmake . 
Probably due to a change in github actions cmake version (see [here](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#command:cmake_minimum_required)).
With this PR we patch the pybind version to v2.13.0 and change the cmake_minimum_required(VERSION 2.8.12...3.30) in the nestpy cmake list. 
See also https://github.com/NESTCollaboration/nestpy/issues/113
=> Patch cmake version in nestpy

fuse/plugins/pmt_and_daq/pmt_response_and_daq.py
Use `strax.stable_sort` instead of `np.sort`, and add sorting to `pulse_groups` as well.
=> Daq photon sorting

fuse/plugins/detector_physics/electron_drift.py
This PR is an alternative solution to #296.
As suggested by @sebvetter , a better solution than hardcoding the value of Z for the FDC map boundaries as in #296 , here we clip the positions that we pass to the map to the boundaries of the validity of the map (that we get from the map coordinate system). 
The results seem to give the required behaviour, here comparing clipped vs unclipped DeltaR as a function of Z, for a given R.
=> Clip FDC input positions

fuse/context.py, fuse/context_utils.py
Allow flexible overwrite of straxen configs from fuse config file. 
I will remove the fdc_map_mc from the new config format, and leave the old way of treating the fdc map in the fuse context.
In this way the new fuse version would be compatible with both newer and older config files, but old fuse versions not compatible with new config file (potentially dangerous as it would ignore the overwrite).
Supports formats like: 
```
"mc_overrides": {
"s1_xyz_map": ["XnT_S1_xyz_123.json", "itp_map://resource://MAP_NAME?fmt=json"]
"fdc_map": "itp_map://resource://XnT_S1_xyz_123.json?fmt=json"]
}
```
in the config file, as in https://github.com/XENONnT/private_nt_aux_files/pull/424.
=> MC override in context config

pyproject.toml
The python 3.9 was previously removed in https://github.com/XENONnT/fuse/pull/285
Because we want fuse to be still compatible with straxen v2.0 (https://github.com/XENONnT/fuse/pull/298), we have to support python 3.9
=> Add back support of python 3.9

fuse/context.py, fuse/context_utils.py
This PR confines the code for writing `run_id` into lineage within a single function, `write_run_id_to_config`.
The PR allows `corrections_run_id` to be None, by setting `run_without_proper_run_id=True`.
=> Allow None `corrections_run_id`

fuse/plugins/micro_physics/lineage_cluster.py, fuse/plugins/micro_physics/merge_cluster.py
Positrons were mistakenly classified as `'nontype'`.
Modified a line to classify `'e+'` to be beta-like.
=> fix positrons cluster classification in MergeCluster.classify

fuse/context_utils.py, fuse/plugins/detector_physics/s2_photon_propagation.py
We want to be able to define the interpolation method of the s2 pattern map. 
We leave as default the `WeightedNearestNeighbors`. 
We will change it accordingly in the simulation config files using the mc_overrides key.
=> Add s2_pattern_map_interpolation_method

fuse/common.py, fuse/plugins/detector_physics/csv_input.py, fuse/plugins/detector_physics/delayed_electrons/photo_ionization_electrons.py, fuse/plugins/detector_physics/s1_photon_propagation.py, fuse/plugins/detector_physics/s2_photon_propagation.py, fuse/plugins/detector_physics/secondary_scintillation.py, fuse/plugins/micro_physics/find_cluster.py, fuse/plugins/micro_physics/input.py, fuse/plugins/micro_physics/lineage_cluster.py, fuse/plugins/pmt_and_daq/pmt_afterpulses.py, fuse/plugins/pmt_and_daq/pmt_response_and_daq.py, fuse/plugins/truth_information/event_truth.py, fuse/plugins/truth_information/peak_truth.py, fuse/plugins/truth_information/records_truth.py
This PR was initiated when I found that the `propagated_s1_photons` and `propagated_s2_photons` are not deterministic, i.e., the result will be a little bit different each time I submit a job.
`np.sort` and `np.argsort` in fuse are only partially changed to `stable_sort` and `stable_argsort`. This PR applies stable sorting to all sorting in fuse.
Depends on https://github.com/AxFoundation/strax/pull/918 and https://github.com/XENONnT/fuse/issues/298
=> Use stable `sort` and `argsort` to avoid indeterministic result

fuse/plugins/micro_physics/input.py
I understand the `cut_delayed` was set as 9e18, which is a bit smaller than `np.iinfo(np.int64).max` (9223372036854775807). But for `strax.sort_by_time` to work, the "maximum" possible time difference can only be about 4.5e18 because:
1. For some reason, `np.sort` can not work when the max time is larger than `np.iinfo(np.int64).max`
2. The placeholder `channel` is conservatively set as `np.ones(len(x))`, so as long as the max time is larger than about 4.5e18, the `strax.sort_by_time` will use `np.sort` rather than `strax.processing.general._sort_by_time_and_channel`.
Also, the 9e18 is too large, is it about 300 years.
Set `cut_delayed` as 1e18 so that the …
=> Reduce `cut_delayed` to be much less than `np.iinfo(np.int64).max`

fuse/plugins/micro_physics/lineage_cluster.py
Different `eventid` can overlap in time of `geant4_interactions`. `geant4_interactions` is sorted in time, but the returned values of `build_lineages` are sorted in `eventid`.
Sort `geant4_interactions` by `eventid` and time, run `build_lineages`, and finally recover the order of `interaction_lineage` according `geant4_interactions`.
=> Fix bug caused by event id time overlapping in `interaction_lineage `

fuse/context_utils.py, fuse/plugins/detector_physics/s1_photon_hits.py
Proposal to apply the lce function directly in plugin and not in the url config. 
This is becuase it makes it quite confusing when changin the s1 pattern map config, that the lce is not also updated... 
This way, changin s1 pattern map config makes both changes at the same time, pattern and lce. 
---
To be more clear, there is not change in the implementation. 
Just that now, if changing only s1_pattern_map with st.config, s1 lce would not change.
With this PR (and before <1.5.0), changing s1_pattern_map also changes lce - makes more sense and less prone to errors. 
Thanks to @kboese-mpik for realising this (and sorry for causing you this pain!)
=> Implement lce_from_pattern_map function directly in plugin
